channels:
- conda-forge
dependencies:
- python=3.9.23
- pip<=25.1
- pip:
  - mlflow==3.1.4
  - numpy==2.0.2
  - pandas==2.3.1
  - psutil==7.0.0
  - scikit-learn==1.6.1
  - scipy==1.13.1
  - xgboost==2.1.4
name: mlflow-env
