channels:
- conda-forge
dependencies:
- python=3.12.1
- pip<=25.1.1
- pip:
  - mlflow==3.4.0
  - numpy==2.3.1
  - pandas==2.3.1
  - psutil==7.0.0
  - scikit-learn==1.7.0
  - scipy==1.16.0
  - xgboost==3.0.5
name: mlflow-env
